Update pypi-release.yml

diff --git a/.github/workflows/pypi-release.yml b/.github/workflows/pypi-release.yml
--- a/.github/workflows/pypi-release.yml
+++ b/.github/workflows/pypi-release.yml
@@ -8,38 +8,39 @@ on:
       - 'v*'
   workflow_dispatch:
 
-  jobs:
-    build-artifacts:
-      runs-on: ubuntu-latest
-      if: github.repository == 'euroargodev/argodmqc_owc'
-      steps:
-        - uses: actions/checkout@v4
-          with:
-            fetch-depth: 0
-        - uses: actions/setup-python@v5
-          name: Install Python
-          with:
-            python-version: 3.8
+jobs:
+  build-artifacts:
+    runs-on: ubuntu-latest
+    if: github.repository == 'euroargodev/argodmqc_owc'
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-python@v5
+        name: Install Python
+        with:
+          python-version: 3.13
 
-        - name: Install dependencies
-          run: |
-            python -m pip install poetry
-            poetry build
+      - name: Install dependencies
+        run: |
+          python -m pip install poetry
+          pip install twine
+          poetry build
 
-        - name: Check built artifacts
-          run: |
-            python -m twine check dist/*
-            pwd
-            if [ -f dist/pyowc-0.0.0.tar.gz ]; then
-              echo "❌ INVALID VERSION NUMBER"
-              exit 1
-            else
-              echo "✅ Looks good"
-            fi
-        - uses: actions/upload-artifact@v4
-          with:
-            name: releases
-            path: dist
+      - name: Check built artifacts
+        run: |
+          python -m twine check dist/*
+          pwd
+          if [ -f dist/pyowc-0.0.0.tar.gz ]; then
+            echo "❌ INVALID VERSION NUMBER"
+            exit 1
+          else
+            echo "✅ Looks good"
+          fi
+      - uses: actions/upload-artifact@v4
+        with:
+          name: releases
+          path: dist
 
 #   test-built-dist:
 #     needs: build-artifacts
