Update pypi-release.yml

diff --git a/.github/workflows/pypi-release.yml b/.github/workflows/pypi-release.yml
--- a/.github/workflows/pypi-release.yml
+++ b/.github/workflows/pypi-release.yml
@@ -1,84 +1,78 @@
 name: Build and upload pyowc to PyPI
+
 on:
-#  release:
-#    types: [created, edited]
-#  push:
-#    tags:
-#      - 'v*'
+  release:
+    types: [created, edited]
+  push:
+    tags:
+      - 'v*'
   workflow_dispatch:
 
+  jobs:
+    build-artifacts:
+      runs-on: ubuntu-latest
+      if: github.repository == 'euroargodev/argodmqc_owc'
+      steps:
+        - uses: actions/checkout@v4
+          with:
+            fetch-depth: 0
+        - uses: actions/setup-python@v5
+          name: Install Python
+          with:
+            python-version: 3.8
 
-jobs:
-  build-artifacts:
-    runs-on: ubuntu-latest
-    if: github.repository == 'euroargodev/argodmqc_owc'
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: actions/setup-python@v5
-        name: Install Python
-        with:
-          python-version: 3.8
+        - name: Install dependencies
+          run: |
+            python -m pip install poetry
+            poetry build
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install setuptools setuptools-scm wheel twine check-manifest
+        - name: Check built artifacts
+          run: |
+            python -m twine check dist/*
+            pwd
+            if [ -f dist/pyowc-0.0.0.tar.gz ]; then
+              echo "❌ INVALID VERSION NUMBER"
+              exit 1
+            else
+              echo "✅ Looks good"
+            fi
+        - uses: actions/upload-artifact@v4
+          with:
+            name: releases
+            path: dist
 
-      - name: Build tarball and wheels
-        run: |
-          git clean -xdf
-          git restore -SW .
-          python -m build --sdist --wheel .
+#   test-built-dist:
+#     needs: build-artifacts
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/setup-python@v5
+#         name: Install Python
+#         with:
+#           python-version: 3.8
+#       - uses: actions/download-artifact@v4.1.8
+#         with:
+#           name: releases
+#           path: dist
+#       - name: List contents of built dist
+#         run: |
+#           ls -ltrh
+#           ls -ltrh dist
 
-      - name: Check built artifacts
-        run: |
-          python -m twine check dist/*
-          pwd
-          if [ -f dist/pyowc-0.0.0.tar.gz ]; then
-            echo "❌ INVALID VERSION NUMBER"
-            exit 1
-          else
-            echo "✅ Looks good"
-          fi
-      - uses: actions/upload-artifact@v4
-        with:
-          name: releases
-          path: dist
+#       - name: Verify the built dist/wheel is valid
+# #        if: github.event_name == 'push'
+#         run: |
+#           python -m pip install --upgrade pip
+#           python -m pip install dist/pyowc*.whl
+# #          python -m parcels.util.print_versions
 
-  test-built-dist:
-    needs: build-artifacts
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/setup-python@v5
-        name: Install Python
-        with:
-          python-version: 3.8
-      - uses: actions/download-artifact@v4.1.8
-        with:
-          name: releases
-          path: dist
-      - name: List contents of built dist
-        run: |
-          ls -ltrh
-          ls -ltrh dist
-
-      - name: Verify the built dist/wheel is valid
-#        if: github.event_name == 'push'
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install dist/pyowc*.whl
-#          python -m parcels.util.print_versions
-
-      - name: Publish package to TestPyPI
-#        if: github.event_name == 'push'
-        uses: pypa/gh-action-pypi-publish@v1.10.1
-        with:
-          user: __token__
-          password: ${{ secrets.PYPITEST_TOKEN }}
-          repository_url: https://test.pypi.org/legacy/
-          verbose: true
+#       - name: Publish package to TestPyPI
+# #        if: github.event_name == 'push'
+#         uses: pypa/gh-action-pypi-publish@v1.10.1
+#         with:
+#           user: __token__
+#           password: ${{ secrets.PYPITEST_TOKEN }}
+#           repository_url: https://test.pypi.org/legacy/
+#           verbose: true
 
 
 #  upload-to-pypi:
